services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    ports:
      - "127.0.0.1:5000:5000"
    restart: unless-stopped
    environment:
      - LT_LOAD_ONLY=en,ru,de,es,fr,it,pl,pt,ko,zh,zt
    volumes:
      - libretranslate_models:/home/libretranslate/.local

volumes:
  libretranslate_models: